# Route
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: istio-ingressgateway
  namespace: {{ .Values.istioIngressGateway.namespace }}
spec:
  host: "{{ .Values.istioIngressGateway.hostname }}"
  port:
    targetPort: http2
  to:
    kind: Service
    name: {{ .Values.istioIngressGateway.name }}
    weight: 100
  wildcardPolicy: None
#---
# Allow outside traffic to access the gateway
# This is optional, only needed in case your cluster contains restrictive NetworkPolicies
#apiVersion: networking.k8s.io/v1
#kind: NetworkPolicy
#metadata:
#  name: gatewayingress
#  namespace: {{ .Values.istioIngressGateway.namespace }}
#spec:
#  podSelector:
#    matchLabels:
#      istio: ingressgateway
#  ingress:
#    - {}
#  policyTypes:
#  - Ingress

