# Aplicamos el rol con permisos de escritura a la sa del colector
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tempostack-traces
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tempostack-traces-write
subjects:
  # El nombre de la sa del paso anterior
  - kind: ServiceAccount
    name: otel-collector
    namespace: istio-system