#----------------------------------------------------------------------------------
# Installs the kiali operator
#----------------------------------------------------------------------------------
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali-operator
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: openshift-operators
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
  source:
    repoURL: https://github.com/rlnieto/istio.git
    targetRevision: main
    path: service-mesh-deployments/v3/helm-charts/kiali-operator
       
