# Control plane service monitor
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istiod-monitor
  namespace: {{ .Values.istio.namespace }}
spec:
  targetLabels:
  - app
  selector:
    matchLabels:
      istio: istiod
  endpoints:
  - port: http-monitoring
    interval: 30s
