apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.istioIngressGateway.name }}
  namespace: {{ .Values.istioIngressGateway.namespace }}
spec:
#  type: ClusterIP
  type: NodePort
  selector:
    istio: ingressgateway
  ports:
  - name: http2
    port: 80
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 8443

