#----------------------------------------------------------------------------------
# Installs the open telemetry operator
#----------------------------------------------------------------------------------
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-operator
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: openshift-opentelemetry-operator
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
  source:
    repoURL: http://github.com/rlnieto/istio.git
    targetRevision: main
    path: service-mesh-deployments/v3-gw-api/helm-charts/otel-operator
       
