#----------------------------------------------------------------------------------
# Installs the istio ingress gateway
#----------------------------------------------------------------------------------
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingressgateway
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: istio-ingress
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
  source:
    repoURL: http://papandujo.tia.com:3000/rlnieto/istio.git
    targetRevision: main
    path: basic-deployment/v3-gw-api/helm-charts/istio-ingressgateway
       
