#----------------------------------------------------------------------------------
# Deploys the bookinfo application
#----------------------------------------------------------------------------------
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo-application
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
  source:
    repoURL: https://github.com/rlnieto/istio.git
    targetRevision: main
    path: deployments/v3-ambient-sidecar-otel/helm-charts/bookinfo-application
       
