# Secret con las credenciales de acceso a minio
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.minio.name }}
  namespace: {{ .Values.minio.namespace }}
type: Opaque
stringData:
  endpoint: {{ .Values.minio.endpoint }}
  bucket: {{ .Values.minio.bucket }}
  access_key_id: {{ .Values.minio.access_key_id }}
  access_key_secret: {{ .Values.minio.access_key_secret }}
  insecure: "true"  # HTTP (sin TLS)
